# Generated by Django 2.0.6 on 2018-07-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='subject_type',
            field=models.CharField(choices=[('Language', 'Language'), ('Database', 'Database'), ('Etc', 'Etc')], default='Etc', max_length=10, verbose_name='Subject Type'),
        ),
    ]
