# Generated by Django 2.1 on 2018-08-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180830_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='author',
        ),
        migrations.RemoveField(
            model_name='board',
            name='password',
        ),
    ]
