# Generated by Django 2.0.6 on 2018-07-07 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180708_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='categoryname',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='board.Category'),
        ),
    ]
