# Generated by Django 2.0.6 on 2018-07-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180708_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='hit',
        ),
        migrations.AddField(
            model_name='board',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
