# Generated by Django 2.0.6 on 2018-07-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20180705_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
