# Generated by Django 2.0.6 on 2018-07-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20180708_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='updated',
        ),
    ]
