# Generated by Django 2.0.6 on 2018-07-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20180706_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
